conf/layers.txt: Use latest revisions from master
bitbake:
12d43cf codeparser: Use hashlib for hashing, not hash()
633c0c1 codeparser: Small optimisation to stop repeated hash() calls
17ff08d fetch2: fix unpacking of deb packages
e5986c7 fetch2/git.py: References must match exactly
32c9689 cookerdata: print an error if layer dir does not exist
a609ad7 bitbake-layers: show-layers: disable parsing
fde5c96 toaster: use python3 explicitly
b91aa29 toaster: fix urllib imports
c3ff90c toaster: don't use mru.count in the template
0c38441 toaster: use // operator instead of /
750ca5c Revert "buildinfohelper: work around unicode exceptions"
ceb6e5b xmlrpc: add parameter use_builtin_types
b9a9ddf toaster: use knotty when working with bitbake server
9a6b211 toaster: fix migrations
0c5d691 toaster: moved import bb.server.xmlrpc
1414866 toaster: read timezone files in binary mode
7cc3a41 toaster: use re.sub() instead of translate()
d41eb6d toaster: replace map with list comprehensions
372dd3a toaster: use items and range instead of old APIs
752ea00 toaster: use decode('utf-8') for binary data
46f185a toaster: modified list of dependencies
3f1e68c toaster: fix local imports
1abaa1c toaster: fix imports to work for python 3
249d0bc toaster: get rid of using reduce
9dd9c13 toaster: use force_text instead of force_bytes
ee7df1c goggle/image-writer: Drop since bitrotting and no longer used
c53c741 image-writer/goggle: Disable pygtkcompat problems
7103516 lib/bb: Set required python 3 version to 3.4.0
b19a4c5 data_smart: Simplify ExpansionError exception
d0f904d bitbake: Convert to python 3
bf25f05 bitbake: Drop futures usage since we're python 3
5ee80d7 bitbake/pyinotify.py: Upgrade to py3 version
2f4b98a bitbake/bs4: Upgrade 4.3.2 -> 4.4.1 (python 3 version)

openembedded-core:
a91a603 testexport.bbclass: Create tarballs for easy release
05e6c89 testexport.bbclass: Add support for testexport-tarball
d787cd3 testexport-tarball.bb: Add recipe
5a4c73b testimage.bbclass: Make dependency of cpio when using RPMs
b7111d9 oetest.py: Add install/uninstall functionality for DUTs
a26f23d lib/oeqa/otest.py: Fix import tests from other layers with python3
0440b5a oe/lib/pacakge_manager.py: Update missing pipeline decoding
8369070 alsa-plugins: 1.1.0 -> 1.1.1
f54d2d6 alsa-utils: 1.1.0 -> 1.1.1
3693f24 alsa-lib: 1.1.0 -> 1.1.1
2190658 alsa: update BUGTRACKER links
4b0b43f opkg-utils: update SRCREV
9d23daf rm_work: exclude all kernel recipes
db702fb gobject-introspection: move to Python 3
8ea6be5 db: add RECIPE_NO_UPDATE_REASON
9161b08 linux-yocto/4.4: mmc backports
8933893 yocto-bsps: add i2c definitions to beaglebone
10ddce2 linux-yocto/4.4: bump to v4.4.12
e18657d meta: Drop swabber
554719e lib/oe/package_manager: adapt for Python 3
84fe3f2 libarchive: respect disable-acl configuration option
6e7d9dd image-buildinfo: Update to python3 syntax
f12fe90 libarchive: Add PACKAGECONFIG for lz4 to ensure determinism
3812f58 dpkg: Upgrade to 1.18.7
374e3a0 ofono: update to 1.18
bafe31e gnome-desktop3: update to 3.20.2
e25b27c watchdog: update to 5.15
1310a71 systemtap: update to 3.0
c4f5805 msmtp: update to 1.6.5
f832175 libxslt: update to 1.1.29
eeb5b00 libksba: update to 1.3.4
4a0eed2 kexec-tools: update to 2.0.12
f8a0a8f iso-codes: update to 3.68
91d230d icu: update to 57.1
9689cd9 mc: update to 4.8.17
7070c02 gobject-introspection: update to 1.48.0
1c2f1be gdb: fix upstream check
831ef4c gcc: fix upstream check for 5.x version
3a6c9cc cantarell-fonts: update to 0.0.24
3b83e8c ffmpeg: update to 3.0.2
f969c62 build-appliance-image: update version to 15.0.0
531b617 btrfs-tools: update to 4.5.3
25d4129 boost: update to 1.61.0
818034c cantarell-fonts: fix upstream check
f5dd9d5 tzcode, tzdata: fix upstream version check
7bb667e cups: fix upstream version check
566ca29 webkitgtk: upgrade to 2.12.3
2b6c5cc rt-tests, hwlatdetect: upgrade to 2.0
81fa61c gdbm: upgrade to 1.12
b966830 toasterconf.json: exclude releases Toaster can't build
0eadd00 scripts/pybootchart: Fix print statement
b3f4de7 send-error-report: encode data to bytes
cfae302 lib/oe/buildhistory_analysis: fix for Python 3
4a95989 security_flags.inc: add an entry for python3-numpy
9129af6 testexport.bbclass: Update to use python3
5d73c59 dosfstools: Upgrade 3.0.28 -> 4.0
334e32a image-live, image-vm, wic: Remove fs size workaround
970cdbe mtools: Patch out a useless sanity check
523c99a ca-certificates: add dependency for native/nativesdk on openssl-native
4b544ff scripts: python3: change python to python3 in shebang
ae4d363 scripts: python3: decode subprocess output
bf1b411 combo-layer: python3: use tempfile.TemporaryFile
391cd33 dirsize: python3: fix TypeError: unorderable types
f9bda8b combo-layer: python3: import reduce
067a215 scripts: python3: use new metaclass syntax
77ae2da scripts: python3: get rid of __future__ imports
3276515 scripts: python3: rename raw_input to input
10529d8 ksize.py: python3: get rid of strings.join
ec3f175 scripts: python3: fix urllib imports
438eabc scripts: python3: use new style except statement
874a269 scripts: python3: convert iterables to lists
0c85665 automake: drop the Python scriptlets to determine Python's directories
d08f523 python3-numpy: add a recipe
4aa0d34 hwlatdetect: move to Python 3
671a8e5 libcap-ng: move to Python 3
fa707f7 systemtap: move to Python 3
f49beaf lttng-ust: move to Python 3
e0cd0bd lttng-tools: move to Python 3
8ba5fcb gnome-doc-utils: remove recipe
70e39d1 libnewt-python: move to Python 3
b2037a6 libuser: move to Python 3
798db38 python-docutils: move to Python 3
b03ebfa python-imaging: remove unused recipe
976097f python-pyrex: remove unused recipe
aa77072 swig: move to Python 3
675d11c gdb: move to Python 3
c4829e9 bootchart2: move to Python 3
bfd6207 python-pycairo: move to Python 3
0dacdb7 util-linux: move to Python 3
acea8ca systemd: drop python dependency for ptests
91c3d88 nfs-utils: switch to Python 3
f0caf57 packagegroup-core-full-cmdline: drop python-dbus from the list of services
5645bd9 ofono: drop the custom-made revert to Python 2 from Python 3
1e24852 connman: do not install Python test scripts
51250c3 bluez5: switch to Python 3
6334de2 neard: do not package python test scripts
f55e040 python-pygobject: port to Python 3
f0ade81 dbus-test: remove unneeded pygobject dependency
95840a4 glib: move to Python 3
59870a8 python3: drop 110-enable-zlib.patch
691032c python-dbus: update to 1.2.4, port to python 3
a10fd87 bind: switch Python dependency to Python 3.x
e9add1c systemd: support systemd-boot as a stand-alone EFI bootloader
25168b8 pango_1.40.1.bb: Fix compilation error
d904d24 libpam: update dependency list
0c6fc9a iw: update to version 4.7
7718770 libsdl2: Fix build with wayland 1.10
935578c syslinux.bbclass: Added configurable SYSLINUX_ALLOWOPTIONS variable
6c8d187 distro_check.py: Don't mix tabs and spaces
2289138 oeqa/selftest/recipetool.py: Tweak matching of warning line
28a0030 qemurunner: Use surrogateescape decoding
eaf83a5 devtool.py: Fix parsing of bitbake-layers' output
3064d36 buildhistory_analysis: Convert stream data (bytes) to strings
f6df164 selftest/devtool: Compare sets instead of arrays on AssertEqual
fcd6b38 classes/lib: Complete transition to python3
dad9617 scripts: use python3 in shebang
0a064f2 scripts: Fix urlparse imports for python3
de6e98f scripts: Rename ConfigParser -> configparser for python3
30d02e2 scripts: Fix encoding errors for python3
e8cfab0 scripts: Replace basestring -> str for python3
25d4d82 scripts: Fix deprecated dict methods for python3
210e290 qemurunner: convert data when working with socket
23c27d9 wic: encode help text
ea6245d wic: use python3 in shebang
ecfcc5d sanity: Switch urlparse to urllib.parse
d022b43 classes/lib: Update xrange -> range for python3
caebd86 classes/lib: Update to explictly create lists where needed
2476bdc classes/lib: Update to match python3 iter requirements
bb4685a classes/lib: Update to use python3 command pipeline decoding
737a095 classes/lib: Convert to use python3 octal syntax
3dd26cd oe-buildenv-internal: Update to python3
42af63f sanity: Drop setting C locale
85b6a53 scripts/lnr: update for python3
80fecc4 scripts: python3: Use print function
98a4c64 systemd: allow add users as a rootfs postprocess cmd
3d6884a openssl: fix the dangling libcrypto.a symlink
0df6dab package.bbclass: fix strip and split logic
2e49887 perl-ptest.inc: fix tar call to prevent objcopy failure
f97c40f insane: return line-feeds to qa.log
d498b15 bluez5: update to 5.40
5bbde5a libpng: update to 1.6.22
2dd1c02 unzip: fix security issues
4976382 libarchive: Upgrade to v3.2.0
9bffe2f python-numpy: move recipe to own directory
3e171c8 python3: add = to -L linking option only when the path is absolute
3e751bd python3-nose: add a recipe
72be375 python3-mako: add a Python 3 recipe
a5aa151 cracklib: disable building the python module
54cbeb2 subversion: remove unnecessary python dependency
1c8cdcd qemu: remove runtime python dependency
f2383ea git: remove Python package (to which nothing was packaged)
abf2258 python3: manipulate all of the config*/Makefile files, not just config/Makefile
36e9ed8 avahi-ui: remove support for building a python module
79a98af sip.bbclass: remove
e0c7584 default-versions.inc: drop python-related defaults
3891fce python3-dir.bbclass: add a separate class for Python 3
5a149a0 distutils-native-base.bbclass, distutils3-native-base.bbclass: remove
8834e81 python-native, python3-native: remove the use of exported HOST_SYS and BUILD_SYS variables
000480c recipetool / devtool: set a fixed SRCREV by default when fetching from git
13bc243 recipetool: create: use ${BP} for subdir for binary packages
19e6b66 recipetool: create: extract variable values from .deb/.ipk/.rpm
91fc35f recipetool: create: support extracting SUMMARY and HOMEPAGE
c33ba6c lib/oe/recipeutils: fix insertion of variable values
fb2bb50 lib/oe/recipeutils: patch_recipe_lines: allow omitting trailing newlines
d780642 lib/oe/recipeutils: split out patch_recipe_lines()
b746223 linux-yocto/4.1: fix musb compilation error
e3aa87a linux-yocto: only use intel branches for optimized platforms
5bc0ce9 linux-yocto: create intel branches
232320c linux-yocto:4.4: broxton backports
4f5ba49 layer.conf: Whitelist ca-certificate dependency on openssl
a90ba07 ca-certificates: Add openssl as a runtime dependency
2cb1142 initscripts: check if swapon/swapoff exists before executing them
4afee78 uboot-sign: rebuild u-boot.img with signed dtb
b8436a9 u-boot: replace old-style shell syntax with the modern one
a7e7097 xcb-proto: remove stale git recipe and now redundant .inc
476d816 libxcb: upgrade to 1.12
66c3176 xcb-proto: upgrade to 1.12
59dfae0 libsecret: upgrade to 0.18.5
f3add5f liburcu: upgrade to 0.9.2
30d6a73 gcr: upgrade to 3.20.0
16fda75 babeltrace: upgrade to 1.3.2
494d875 msmtp: upgrade to 1.6.4
be18364 gobject-introspection.bbclass: disable introspection for -native and -nativesdk recipes
343f762 lib/oe/package_manager.py: Add pkgpath to dict returned by package_info
49234fe oetest.py: Add support to copy unextracted packages for runtime testing
90d585f oetest.py: Add extract_packages() to RuntimeTestContext class
1f24ef9 oetest.py: Add json file support to specify packages needed in runtime tests
5c70c79 xmlto: xmlto needs tail to run
3493bda libgpg-error: Upgrade 1.21 -> 1.22
dfc9178 gnupg.org-hosted recipes: Change SRC_URI to https site
cab454a libevdev: Upgrade 1.4.6 -> 1.5.1
12b3541 gtk+: Upgrade 2.24.29 -> 2.24.30
594aa27 clutter-gst-3.0: Upgrade 3.0.16 -> 3.0.18
04534fe clutter-1.0: Upgrade 1.24.2 -> 1.26.0
51ba290 coreutils: revert upstream commit causing havoc with ls output
aa215c1 wic: bootimg-efi: include startup.nsh if it's available
43ca968 gummiboot.bbclass: also write startup.nsh for non-iso
ec8dc34 grub-efi.bbclass: also write startup.nsh for non-iso
dcbd86b linux-firmware: update to git rev 80d463be82
ac512ff libpam: update to 1.3.0
df798bc dropbear: Remove incorrect SFTPSERVER_PATH from CFLAGS
1384ccd docbook-xsl-stylesheets: Upgrade 1.78.1 -> 1.79.1
6e58f54 kernel: Make symbol link to vmlinuz in boot directory
849b67b kernel: Add KERNEL_IMAGETYPES to build multi types kernel at one time
fb3457a cpio: Add native variant
9b4b150 oeqa/utils/package_manager.py: Add get_package_manager()
667a454 oetest.py: Move getTests() outside loadTests() method
f4da383 testexport.bbclass: Stop exporting test context
04a2ae6 nopackages.bbclass: deltask foo_setscene
740e346 libjpeg-turbo: set SUMMARY
719a38d gobject-introspection: set SUMMARY and HOMEPAGE
82cf96a argp-standalone: set SUMMARY instead of DESCRIPTION
8fe0b68 signing-keys: set SUMMARY instead of DESCRIPTION
8a5637b fts: set SUMMARY instead of DESCRIPTION
17d85cf bsd-headers: set SUMMARY instead of DESCRIPTION
16c30d8 dhcp: fix non-deterministic libxml2 dependency
d603a6a gcc: Backport nios2 gcc ICE fix
f402225 npm: add target_arch flag to npm
94d80ae ghostcript: Set UPSTREAM_CHECK_URI variable
55e335d sanity: check that the en_US.UTF-8 locale exists
9c21339 diffutils: Add patch to fix gplv2 version with gcc6
c20d863 tcmode-default: Bump gcc

meta-openembedded:
5221399 mpv: Media Player
1847d0b libass: add newer version
e781f8e mpd: update to 0.19.15
d609617 meta-oe: override SECURITY_CFLAGS for llvm3.3
f90b8d3 toybox: Upgrade to 0.7.1
3ff2e22 libftdi: update to 1.3
8b32e60 nginx: update to version 1.11.1
98c4e4f nginx: update stable version to 1.10.1
b5091a1 python-tornado: add missing python2 runtime deps
7650008 python-singledispatch: initial recipe for version 3.4.0.3
4c110ff python-backports-abc: initial recipe for version 0.4
4594d24 syslog-ng: expand service file @variables@ earlier
b27938b opencv: Reorder PACKAGES variable
d0952ad opencv: Make gphoto2 dep optional via PACKAGECONFIG
24fe575 abiword, gnome-vfs: Use print as a function
80cf5e0 netmap-modules: Avoid type warning with python v3
55cb2ec gitkpkgv: Ensure files are closed
b4d7caa gnome-doc-utils-stub: add a recipe
f0de8ed cmpi-bindings: fix build with python 3
a18991d python-pygobject: add a recipe
4f93338 python-pyrex: add a recipe
56a4d21 python-imaging: add a recipe
25a0003 python-dbus: add a recipe
f9ce43c Remove unnecessary exports of HOST_SYS and BUILD_SYS in python-based recipes
e5f01ca nano: fix license to GPLv3.
240e2eb plymouth: allow disabling the dracut dep
852cd67 luajit: fix build issues, obey more vars
0cce9fe efivar-native: fix compile failure with older host gcc (<=4.6)
25f31a5 nodejs: update to 4.4.5
ff41698 gnome-menus: Fix QA warnings.
c2c895e python-simplejson: change to setuptools
350bd0b dvd-apps: Fix several QA WARNINGS
6de06e4 geany-plugins: fix build
7be16bc libldb: add missing libaio dependency
126e48c libtalloc: add missing libaio dependency
81f3fb0 libtdb: add missing libaio dependency
18a1d69 libtevent: add missing libaio dependency
a6a3671 cifs-utils: make samba conditional dependency
d765990 netcat-openbsd: fix qa warning
a2256bb esmtp: Fix rootfs creation errors
7832c67 postfix: Fix rootfs creation errors
62e3df2 netkit-rsh: fix build issue.
880c3dc opensaf: update to 5.0.0
d46c89a squid: CVE-2016-4553
9a13040 ntp: avoid floating dependency on mdns (aka mDNSResponder)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>